### ISSUE TITLE
V 1.0.2 Broken Progression involving Lava Bucket

### ISSUE THREAD

**Issue by Ikarsu** [Tismas/cave-factory#19]
Found a catch 22 within the FTB Quest.

Incorrect Runes in quest book. Quest progression is locked due to catch 22 conditions involving Generating first bucket of lava, needing Magma Cream to make Fire Ritual Runes, but to do so, one needs to visit the Nether first to get Magma Cream, but to visit the Nether, one needs Obsidian, and in order to make Obsidian, one needs lava.

So how can one conduct the Nether Ritual if it's locked to Nether progression due to Fire Rune Inscriber Recipe needing Magma Cream???

**Comment by ghingis** [comment]
No it is not broken, you just do not know blood magic, do not worry me neither it was like an hour to figure it out.. but I managed to do so

- put a master ritual stone and 4 ritual stones in a "+" shape with the master in the middle (check the sanguine scientiem for reference)
- take your `Ritual Diviner` and shift + right click to the air until you see the "serenade of the neter" on the bottom of the screen
- start right clicking onto the middle block with the diviner
- once the ritual stones turn to fire ritual stones right click to the middle block with the activation crystal
- lava starts spawning in the middle

**Comment by Ikarsu** [comment]
I did find an alternative method in the event said Divination Tool ended up being destroyed.

Use of Fel Pumpkins from Botania. Upwards of 6 blaze powder a kill. 

<Thread Closed. Follow tips above to resolve Fiery Stagnantion. Alternative method provided in event Ritual Diviner gets destroyed.>
