### ISSUE TITLE
Wireless crafting grid can't pick up the item in the first slot on the hot bar while the grid is open

### ISSUE THREAD

**Issue by sadfaceman** [Tismas/cave-factory#28]
Opening up the wireless crafting grid, and having an item in the first slot on the hot bar, when attempting to deposit the item from the first slot, the item is locked, and cannot be picked up.
This happens when using the curios slot for the wireless crafting grid.

Cave Factory v1.0.3

**Comment by razgriz5000** [comment]
I think this is a problem with the curios mod.  I have had this problem with other packs as well.

**Comment by razgriz5000** [comment]
I just discovered that https://www.curseforge.com/minecraft/mc-mods/refined-curios is not supported anymore.  seems Refined Storage built in curio support.

**Comment by sadfaceman** [comment]
Lastest update of the modpack fixed this issue
