### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Jordshire** [Tismas/cave-factory#32]
Game crashes just a few seconds into loading, using AT launcher, Java 8 latest update 4gb ram 
[latest.log](https://github.com/Tismas/cave-factory/files/7792770/latest.log)

**Comment by razgriz5000** [comment]
The first thing that stands out is your java version is out of date.  Can you please update java to Java 8 Update 311

**Comment by Jordshire** [comment]
Ive updated and my terminal shows I'm using 'java version "1.8.0_311"' but I'm still having the same problem

**Comment by Jordshire** [comment]
After switching to the curse forge launcher from at launcher it seems to work just fine now, thanks for the help razgriz :)
