### ISSUE TITLE
Modpack Stops Responding just before the menu

### ISSUE THREAD

**Issue by TheAmazingJeh** [Tismas/cave-factory#35]
This has started happening recently and I'm not sure why.

**Comment by TheAmazingJeh** [comment]
Latest.log

https://cdn.discordapp.com/attachments/848478810777321513/926883296519028806/latest.log

**Comment by razgriz5000** [comment]
Update java to a more recent version.  If still having a problem after updating, try a different launcher.  I recommend either GDlauncher or multimc.

**Comment by TheAmazingJeh** [comment]
This seems to have fixed the problem, thanks.
