### ISSUE TITLE
nether portal

### ISSUE THREAD

**Issue by Electroburst76** [Tismas/cave-factory#39]
whenever I leave the nether through the portal I am teleported to a new portal in which I would have to dig or tp to my spawn. I even tried the divide by 8 trick which just dropped me off even further. I hope the next update can fix this slight

**Comment by razgriz5000** [comment]
Check the y coordinates of both portals.  y coordinates do not scale like x and z.  So the y should be the same on both the overworld and nether.  The nether should be 1/8 of the overworld's coordinates.  

I have seen this on "vanilla" servers before, so this is a base minecraft problem, not specific to this pack.

**Comment by Electroburst76** [comment]
ok the portal works now
